package doit.doit;

import doit.doit.Idea;

rule "1: idea is worth it"
    when
        $i : Idea(successChance > 0.5f, $chance: successChance)
    then
        $i.setShouldDoIt(true);
        System.out.println("idea is worth it, success chance is: " + $chance);

end

rule "idea is not worth it"
    when
        $i : Idea(successChance <= 0.5f, $chance: successChance)
    then
        $i.setShouldDoIt(false);
        System.out.println("idea is NOT worth it, success chance is: " + $chance);


end