package doit.doit;

import doit.doit.Idea;

rule "reweard is 1"
    when
        Idea(reward == 1)
    then
        shouldDoIt = true;
        System.out.println("reward is 1!!");
        System.out.println("should do it: "+ shouldDoIt);
end

rule "reweard is NOT 1"
    when
        Idea($reward : reward)
        Idea($reward != 1)
    then
        shouldDoIt = false;
        System.out.println("reward is NOT 1, it is: " + $reward);
        System.out.println("should do it: "+ shouldDoIt);


end