package doit.doit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Idea implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("PK of idea")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("the idea itself")
	@org.kie.api.definition.type.Description("any idea at all...")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("odds of hitting the reward")
	private Float successChance;

	@org.kie.api.definition.type.Label("do it or not")
	private java.lang.Boolean shouldDoIt;

	@org.kie.api.definition.type.Label("downside of failure")
	private java.lang.Float downsideOfFailure;

	@org.kie.api.definition.type.Label("upside of success")
	private java.lang.Float upsideOfSuccess;

	@org.kie.api.definition.type.Label("cost to attempt this idea")
	private java.lang.Float costToAttempt;

	@org.kie.api.definition.type.Label(value = "the type of idea this is")
	private java.lang.String ideaType;

	public Idea() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Boolean getShouldDoIt() {
		return this.shouldDoIt;
	}

	public void setShouldDoIt(java.lang.Boolean shouldDoIt) {
		this.shouldDoIt = shouldDoIt;
	}

	public java.lang.Float getSuccessChance() {
		return this.successChance;
	}

	public void setSuccessChance(java.lang.Float successChance) {
		this.successChance = successChance;
	}

	public java.lang.Float getDownsideOfFailure() {
		return this.downsideOfFailure;
	}

	public void setDownsideOfFailure(java.lang.Float downsideOfFailure) {
		this.downsideOfFailure = downsideOfFailure;
	}

	public java.lang.Float getUpsideOfSuccess() {
		return this.upsideOfSuccess;
	}

	public void setUpsideOfSuccess(java.lang.Float upsideOfSuccess) {
		this.upsideOfSuccess = upsideOfSuccess;
	}

	public java.lang.Float getCostToAttempt() {
		return this.costToAttempt;
	}

	public void setCostToAttempt(java.lang.Float costToAttempt) {
		this.costToAttempt = costToAttempt;
	}

	public java.lang.String getIdeaType() {
		return this.ideaType;
	}

	public void setIdeaType(java.lang.String ideaType) {
		this.ideaType = ideaType;
	}

	public Idea(java.lang.String id, java.lang.String description,
			java.lang.Float successChance, java.lang.Boolean shouldDoIt,
			java.lang.Float downsideOfFailure, java.lang.Float upsideOfSuccess,
			java.lang.Float costToAttempt, java.lang.String ideaType) {
		this.id = id;
		this.description = description;
		this.successChance = successChance;
		this.shouldDoIt = shouldDoIt;
		this.downsideOfFailure = downsideOfFailure;
		this.upsideOfSuccess = upsideOfSuccess;
		this.costToAttempt = costToAttempt;
		this.ideaType = ideaType;
	}

}