package com.doit.do_it;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Idea implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Idea() {
    }




}